model_to_use: "openai" # Options: "openai", "gemini"
analysis_langsmith: true

model_general_parameters:                             # https://community.openai.com/t/cheat-sheet-mastering-temperature-and-top-p-in-chatgpt-api/172683
  temperature_generation_refinement: 0.1
  top_p_generation_refinement: 0.1
  temperature_transformation: 0.4
  top_p_transformation: 0.7
  # max_tokens_transformation: 100                    # the maximum for the model is 4096
  use_examples_vector_database: true

openai_config:
  openai_model_generation_refinement: "gpt-4o"        # "gpt-4-turbo" # "gpt-4-0125-preview"  # "gpt-4-turbo-preview" # For more options, see: https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo
  openai_model_transformation: "gpt-4-turbo"          # This is the model used for the transformation of the user query
  openai_embedding_model: "text-embedding-3-large" # "text-embedding-3-small" # "text-embedding-ada-002"

dev_comments:
  save_logs: false
  include_refinement_process: false
  show_dates_details_extraction: false
  show_developer_comments: false
  show_refined_query: true